### ISSUE TITLE
New line as part of a placeholder-value

### ISSUE THREAD

**Issue by jhs1978** [OpenNTF/POI4Xpages#32]
First of all thank you for this great project! 
Is it possible to have new line as part of the value for the placeholder? 
It seems to work with LibreOffice Writer but not MS Word.

Jan

**Comment by guedeWebGate** [comment]
MS Word handles it different, but I try to fix it.

**Comment by guedeWebGate** [comment]
Could you please try the latest build:
http://www.webgate.biz/ftp/openntf/POI4XPages/snapshot/biz.webgate.dominoext.poi-1.3.0-SNAPSHOT.zip

Btw there is a mailinglist in place to be informed about development builds:
http://mm.wgcdev.ch/mailman/listinfo
