### ISSUE TITLE
problem with datasource from another database

### ISSUE THREAD

**Issue by dregos** [OpenNTF/POI4Xpages#33]
Hi! When I try to use datasource from another database, which is on the same server and is already used as a datasource for my views I don't get any data in excel file. Excel file is created, template used but rows are empty. A have used your example database to see if made a mistake when configuring and copied it and pointed the data source back to the original copy and it does not work. It works when I use current database as source. Maybe the problem is in somwhere arround the line where it says DB is not current DB? Maybe here it wants to work with current database instead of the database provided and therefore view is not found and also an entry is null. I have tested if the database is oppened and entered a fake db path as a source but your code catches that just fine and returns a good log as in "database has not been opened yet"

Here are the first few lines of domino log, which I think are relevant.
31.03.2015 08:31:03 HTTP JVM: BOLJ FINO: First getting the File (biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor)
31.03.2015 08:31:04 HTTP JVM: INFO: Recycle -> DB is not currentDB (biz.webgate.dominoext.poi.util.DatabaseProvider)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Push the Result to the HttpServlet (biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Proccess Spread Sheet (biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Proccess Cell Values (biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Proccess ExportDefinition (biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Proccess Export Row (biz.webgate.dominoext.poi.component.kernel.workbook.EmbeddedDataSourceExportProcessor)
31.03.2015 08:31:04 HTTP JVM: BOLJ FINO: Load Access Source (biz.webgate.dominoext.poi.component.kernel.workbook.EmbeddedDataSourceExportProcessor)
31.03.2015 08:31:05 HTTP JVM: Build collection with Key: (0)
31.03.2015 08:31:05 HTTP JVM: INFO: Recycle -> DB is not currentDB (biz.webgate.dominoext.poi.util.DatabaseProvider)
31.03.2015 08:31:05 HTTP JVM: BOLJ FINO: Start Processing Cells (biz.webgate.dominoext.poi.component.kernel.workbook.EmbeddedDataSourceExportProcessor)
31.03.2015 08:31:05 HTTP JVM: NotesException: Object has been removed or recycled
31.03.2015 08:31:05 HTTP JVM: at lotus.domino.local.NotesBase.CheckObject(Unknown Source)
31.03.2015 08:31:05 HTTP JVM: at lotus.domino.local.ViewEntryCollection.getFirstEntry(Unknown Source)

**Comment by xpagesbeast** [comment]
I'm having a similar issue with no rows (except the header) using the wgpoi:csv CSV Exporter.  I have all this working when the view is in the current database.  I do get the correct document count with the key value in the server console when testing when the view is in another database.

When testing in the NSF that works (view is in same database) there is no stack trace printed to screen.

When running a version where the view is in another database (same server) I get the download in my browser, but no data rows and a server console stack trace.

04/07/2015 03:18:30 PM  HTTP JVM: Build collection with Key: 201503200-07(34)
04/07/2015 03:18:30 PM  HTTP JVM: NotesException: Object has been removed or recycled
04/07/2015 03:53:27 PM  HTTP JVM:  at lotus.domino.local.NotesBase.CheckObject(Unknown Source)
04/07/2015 03:53:27 PM  HTTP JVM:  at lotus.domino.local.ViewEntryCollection.getFirstEntry(Unknown Source)
04/07/2015 03:53:27 PM  HTTP JVM:  at biz.webgate.dominoext.poi.component.sources.DominoView.accessNextRow(DominoView.java:69)
04/07/2015 03:53:27 PM  HTTP JVM:  at biz.webgate.dominoext.poi.component.kernel.csv.EmbeddedDataSourceExportProcessor.process(EmbeddedDataSourceExportProcessor.java:54)

**Comment by guedeWebGate** [comment]
Could you please try the latest build:
http://www.webgate.biz/ftp/openntf/POI4XPages/snapshot/biz.webgate.dominoext.poi-1.3.0-SNAPSHOT.zip 

Btw there is a mailinglist in place to be informed about development builds:
http://mm.wgcdev.ch/mailman/listinfo

**Comment by dregos** [comment]
Thank you very much! It's working now.
