### ISSUE TITLE
can't install on a new domino designer client 9.0.1 FP3

### ISSUE THREAD

**Issue by dregos** [OpenNTF/POI4Xpages#38]
We have recently updated our domino server to 9 and I'am having problems with installing the plugin on my client. I've tried installing via updateSite nsf and by installing as a new feature in D.Designer via Application\Install action. I have installed the new Extension Library with success.
- When installing via update site I get folowing errors(see printscreen):
  ![poi-install_error-by_updatesite](https://cloud.githubusercontent.com/assets/7236463/12390450/75aa0b0e-bde0-11e5-9a09-986dc9a496a5.png)
- And when installing via Application\Install I get "No acceptable features found" message.

**Comment by guedeWebGate** [comment]
The error message on your printscreen is related to FP3. See the following discussion related to this issue: https://www.openntf.org/main.nsf/project.xsp?r=project/XPages%20Extension%20Library/discussions/586418F6A18C7A0B86257DDC004CD309

I'm suprised tht the other way didn't work.

**Comment by dregos** [comment]
Thank you! It has done the trick. I've installed FP4 with interim fixes and then a JVM patch and it worked.
