### ISSUE TITLE
Can not click 2 times the generate XLS button

### ISSUE THREAD

**Issue by flinden68** [OpenNTF/POI4Xpages#39]
I noticed a strange behaviour with a button to generate an Excel sheet on the xlsx_view_objectlistdatasource.xsp page.

When I click the first time, it generate the Excel sheet, but when I click immediately a second time there is nothing happening.
I did not modify anything on  the page, so the button eventhandler is set to Full refresh.

What is going wrong?

**Comment by guedeWebGate** [comment]
http://stackoverflow.com/questions/21930956/poi-4-xpages-document-generation-works-only-once shows you how to fight with that problem ;) We will update the example application later

**Comment by flinden68** [comment]
Christian,

Thanks for the quick reply

Met Vriendelijke Groeten /Sincerely,
Frank van der Linden
Java, Web, XPages, developer/consultant

Phone: +31637394111
Email: flinden68@elstarit.nl
http://elstarit.nl/


On 25 February 2016 at 17:54:02, Christian Guedemann (notifications@github.com) wrote:

http://stackoverflow.com/questions/21930956/poi-4-xpages-document-generation-works-only-once shows you how to fight with that problem ;) We will update the example application later

**Comment by flinden68** [comment]
XSP.allowSubmit() did the trick
